### PR TITLE
Sign Up Form

### PR DESCRIPTION
**Pull request by vsoch**
I don't have time to style the form itself (as it is I shouldn't have taken the time to do this!) but I wanted to give an example of the "pop up" functionality that I had in mind. If you take your current sign in form and plug it into the modal, I think that will look nicely.

I also noticed that you aren't using the native crispy forms? I recommend that you look at forms.py under the statmaps application, and render the forms using that (instead of manually). Take a look at the main collections page if you need an example.

### CODE REVIEW

**Comment by burnash** [comment]
Thanks for the PR. I'm away from home today with limited access to the Internet. I'll take a closer look as soon as I get home.

Yes, I didn't use crispy at first (for the Sign In form), but luckily I had found the reference to it in NeuroVault's code before I did the Sign Up form. The Sign Up form is in a different branch which I forgot to push to the GitHub.

I've just pushed it to https://github.com/burnash/NeuroVault/tree/restyle-sign-in-sign-up

**Comment by burnash** [comment]
@vsoch I've checked the PR and I really like this approach. It makes much better UX than tabs. If I get your idea right, the actual html for the modal form is included in every page for unauth user so when the user presses "Log In" (or "Sign Up") in the navigation, no additional requests are made to the server and the modal just pops up (à la Reddit's Sign In.)

**Comment by vsoch** [comment]
:D

**Comment by vsoch** [comment]
Can't wait to see it all come together! NeuroVault is getting quite a spiffy new look :)

**Comment by burnash** [comment]
@vsoch I've added pop up forms. Could you please check this branch:

https://github.com/burnash/NeuroVault/tree/restyle-sign-in-sign-up

Both _Log In_ and _Sign Up_ pop ups submit data using Ajax and display errors without reloading the page. 

screen shot 2015-06-20 at 03 34 49

screen shot 2015-06-20 at 03 37 07

**Comment by vsoch** [comment]
The pictures look great! I'm finishing up work for today, but I'll be able to give you feedback first thing tomorrow. If there are details with regard to design I'll send a PR so I can share exactly any tweaks that I want to suggest. Great work!

**Comment by vsoch** [comment]
This is great work! So the first distinction that I want to make is between sign up and log in, because I think I was thinking one thing but didn't communicate it clearly:
1. Log in form looked perfect - clean and simple:

login

The issue was that it was not distinct from the sign up, so I suggested the pop up, with something like this in mind:

73161e98-16fe-11e5-8aec-ed93f337489d

but I didn't mean to extend that to the log in as well - because we want them to be distinct to not need the extra labeling, etc.  There is something a little more commercial, a little bit removed about having the sign up be a pop up. It's actually appropriate for a sign up form, because the user is still disconnected/distant from the site, and so the first level of entry is from 100 feet above. But the log in? We want it to be the exact opposite - physically connected / attached to the site, because once the user is a member (has a log in), being logged out means just standing at the threshold.  Further, a pop up once in a while that we want to see (sign up form) is fancy, and surprising. But at a regular frequency they feel more like annoying spam. So we want to use it selectively for the "ooh, ahh" unexpected reaction, but not do it overkill to do away with the effect.

So I would restore the log in to the previous clean version, sans pop up, as shown in the picture above! I will give feedback on the details of the sign up tomorrow, as promised.

**Comment by burnash** [comment]
Yes, let's put the log in back to a regular page. That's actually pretty easy and will even simplify some scenarios.

I'm looking forward to your feedback on the sign up.

**Pull request closed without merging**
