### PR TITLE
Restyle sign in sign up

### PR DESCRIPTION
**Pull request by vsoch**
Here are my suggestions:
- remove header from sign in, as well as gray border on bottom
- align top of modal to be even with bottom of navigation
- modal spacing on top/sides is more even
- add "log in" button to bottom of Sign In (in case they need to go back)

modal

And I wasn't sure where the old log in page was, but the spacing should be like this:

login

(I found an old version, I think, and there wasn't quite enough space).

I leave it to you to restore the old (non-modal) log in and get all the buttons working! And then delete any files not being used.

### CODE REVIEW

**Comment by burnash** [comment]
Good, I'm on it. Do you think we need to add "Sign Up" button to the top navigation bar?

> So the answer is not to fiddle over how salient the "sign up" is on the login page, but to add a more clear "sign up" option from the getgo, in the main navigation when the user is not logged in.

https://github.com/NeuroVault/NeuroVault/pull/278#issuecomment-111855883

**Comment by vsoch** [comment]
Yes, most definitely! I actually thought of this during my work this morning, and forgot to mention it. Most sites we were looking at have a "Log In" and "Sign Up" button in the top right. I haven't looked much at alternative designs yet though.

**Comment by vsoch** [comment]
here is the most obvious design I can think of - buttons blending in (btn-primary class) with the header:

buttons

```
      <ul class="nav navbar-nav navbar-right">
      <li><button class="btn btn-small btn-primary login-required" style="margin-top:8px; margin-right:5px" href="/accounts/profile/">Log in</button></li>
      <li><button class="btn btn-small btn-primary login-required" href="/accounts/profile/" style="margin-top:8px">Sign Up</button></li>
       </ul>
```

**Comment by burnash** [comment]
Yeah, I'm also looking into this direction. The other way is to put a regular link:

screen shot 2015-06-21 at 00 18 10

(I've left _Log in_ in the corner because that's where the username appears after logging in.)

Or something akin to [Wrapbootstrap](http://wrapbootstrap.com):

screen shot 2015-06-21 at 00 27 14

**Comment by vsoch** [comment]
I think that we would want "log in" and "sign up" to be distinguished from the links on the left. When it is just "log in" this is done with separation from the rest, but with two labels we lose that effect. So I would say we should not use a regular link. I don't particularly like the icon afforded by WrapBootstrap either.  I'm not sure if we have other options, but out of the three above I think the subtle btn-primary serve the dual purpose of 1) matching the site without popping out horrifically (imagine if the buttons were white or green), and 2) still being distinguished from the text links on the left of the bar.  What is your preference?

**Comment by burnash** [comment]
Good point on separation. I agree. Let's use buttons.

It turns out Bootstrap has a [special class](http://getbootstrap.com/components/#navbar-buttons) `.navbar-btn` for buttons in the navbar with proper size and vertical alignment.

**Comment by vsoch** [comment]
Eggcellent! :egg:

**Comment by burnash** [comment]
I've removed the Log in pop up, moved extra inlined styles to styles.css and merged the PR. Can you recheck on your side so I can submit a new PR to NV.

**Comment by vsoch** [comment]
Yes, give me just a few minutes.

**Comment by vsoch** [comment]
Ok, here are some comments:
- Log in and sign up look good! I tested the links going back and forth from one to the other, and everything seems working.
- The one functionality that I think we might want to add is pressing "ESC" to close the modal. I think the default is for [keyboard to be true](http://getbootstrap.com/javascript/#js-programmatic-api), but for some reason it doesn't work in this case.

Do we want to style these forms / submit buttons?

New password
profile-password

Edit profile
edit-profile

The "user profile" (making the page a little more substantial) I think is outside the scope of this PR, but maybe fixing up the above two forms, since they are related to log in / sign up, might be a good thing to do! If you don't think so, the PR could definitely go without it, but I think those forms stick out like a sore thumb :+1:

**Comment by burnash** [comment]
Great! Thanks for finding the ESC issue. Got it fixed: 71052ceb70. That was due to missing `tabindex` attribute.

How do you think we should style the remaining forms? If we can use the similar layout as in _Log in / Sign up_ I think I'll be able to find time to finish that. What type of caption (if any) will work for that forms?

**Comment by burnash** [comment]
As for the _user profile_, I think it's a good idea to put some useful info there. Own collections or maybe "favorite" or "saved". It depends on typical use cases.

Now I'm on another, somewhat unrelated to this PR ux problem. I'm improving the csv metadata upload page after yours & Chris's comments. I've added a csv example file and a button to download csv template with image filenames.

Could you please take a look at the draft to see if there are better ways to improve the ui?

screen shot 2015-06-21 at 03 37 43

A click on "View CSV file format" (or on "List image filenames") toggles a collapsed content:

screen shot 2015-06-21 at 03 38 27

I decided to put the additional information into collapsed sections to have cleaner UI.

**Comment by vsoch** [comment]
I'd be happy to! I'm just arriving home and need to do dinner and stuffs, but again I'll be back on this first thing tomorrow. Stay tuned :O)

**Comment by vsoch** [comment]
Here is feedback on the forms, first. I'll want to pull the meta data branch to properly look at it.
- The "forgot password" would both look and function best as a modal:

forgotpw

The reason is because the user is likely to click this from the login form, it should pop up over it, and then when they submit they are again at the login form, making it easy to log back in when the password is sent.  I can't test what is supposed to happen when the button is clicked because I get a Mandrill error.

When we do have a user profile, my thinking is that we will want to use tabs. The typical approach is to have an avatar toward the left (or upper left) and then different tabs for various groups of content.  What are your thoughts on having an avatar? I always liked being able to have one, and users that don't / don' care can have some kind of dummy image ([gravatar?](https://github.com/jezdez/django-avatar)).  For tabs - likely one with privacy / user info (username, email, change password), and then (for now) a My Collections tab. This would likely get more substantial when we add cooler stuff that can be stored with a user. And again, I think this amount of work would be outside of this PR. But it's good to start thinking about.

For the edit profile, the "final" style will likely be a mirror of the user profile, but with the fields editable, so for now I think it would be reasonable to just style the form with bootstrap 3, and have it oriented to the left of the page. The same for the change password form. Unless we are committing to including a user profile with this PR, we really just want those forms to look a little more styled and matching the site, as opposed to figuring out their "final" look (which would require designing the user profile).

What branch is the meta data work on? I can take a look at that next.

**Comment by burnash** [comment]
The branch for the meta data is here: 
https://github.com/burnash/NeuroVault/tree/import-images-meta-data-integrating-fixed-fields

I've just added a url to download a csv template with the image filenames. So there's not dummy buttons on the page now. Can you take a look?

**Comment by vsoch** [comment]
I probably can't take a look today or soon - I just had family come into town and need to go, and am going to be in the hospital tomorrow until later in the week. I can give feedback after that, which is unfortunately not soon. Sorry :(

**Comment by burnash** [comment]
It's ok, I'm almost done with it so I'm going to resubmit the matadata PR anyway. Get well soon!

---

Back to the password reset.

> The reason is because the user is likely to click this from the login form, it should pop up over it, and then when they submit they are again at the login form, making it easy to log back in when the password is sent. 

I don't think it is the case here. After submitting the email address, what the user gets is not an email with the password he could copy & paste straight away, but an email with a link to a page where the user sets a new password. After the user submits the password change form she or he is redirected to a confirmation page:

screen shot 2015-06-22 at 02 01 41

Since after all of this actions the user ends up in a different tab. I doubt the user will search for the original tab, close the reset password pop up and reenter the password to the original log in form. Given the complexity of the reset password workflow I'm not convinced it's practical to implement it with pop up. 

A more practical way is to restyle the pages and give each of them a proper caption. The other question in terms of UX of the reset password workflow is should we go with the default Django behavior and show the user a link to log in page at the final step or to change that and to log in a user straight away.

**Pull request merged**
